_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 17470f7d-5f27-45c9-9a20-aca0e3b58218
name: 'Local News Portal'
mail: sayan.dutta@innoraft.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
